

services:
  # Nosso Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: finance_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - finance_network

  # Interface visual para gerenciar o banco (opcional, mas muito útil)
  pgadmin:
    image: dpage/pgadmin4
    container_name: finance_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - finance_network

networks:
  finance_network:
    driver: bridge

volumes:
  pgdata: